[[about-doc]]
= About the Documentation
:linkattrs:
This section provides a brief overview of Reactor reference documentation. You do not
need to read this guide in a linear fashion. Each piece stands on its own, though they
often refer to other pieces.

== Latest Version & Copyright Notice
The Reactor reference guide is available as HTML documents. The latest copy is available
at https://projectreactor.io/docs/core/release/reference/index.html

Copies of this document may be made for your own use and for distribution to others,
provided that you do not charge any fee for such copies and further provided that each
copy contains this Copyright Notice, whether distributed in print or electronically.

== Contributing to the Documentation
The reference guide is written in
https://asciidoctor.org/docs/asciidoc-writers-guide/[Asciidoc], and you can find its sources at
https://github.com/reactor/reactor-core/tree/master/docs/asciidoc.

If you have an improvement or a suggestion, we will be happy to get a pull request from you!

We recommend that you check out a local copy of the repository so that you can
generate the documentation by running the `asciidoctor` gradle task and checking the
rendering. Some of the sections rely on included files, so GitHub rendering is
not always complete.

ifeval::["{backend}" == "html5"]
TIP: To facilitate documentation edits, most sections have a link at the end that opens
an edit UI directly on GitHub for the main source file for that section. These links are
only present in the HTML5 version of this reference guide. They look like the following:
link:https://github.com/reactor/reactor-core/edit/master/docs/asciidoc/aboutDoc.adoc[Suggest Edit^, role="fa fa-edit"] to <<about-doc>>.
endif::[]

== Getting Help
You can reach out for help in several ways with Reactor:

* Get in touch with the community on https://gitter.im/reactor/reactor[Gitter].
* Ask a question on stackoverflow.com at
https://stackoverflow.com/tags/project-reactor[`project-reactor`].
* Report bugs in Github issues. We closely monitor the following repositories:
https://github.com/reactor/reactor-core/issues[reactor-core] (which covers the
essential features) and https://github.com/reactor/reactor-addons/issues[reactor-addons]
(which covers reactor-test and adapters issues).

NOTE: All of Reactor is open source,
https://github.com/reactor/reactor-core/tree/master/docs/asciidoc[including this
documentation]. If you find problems with the docs or if you want to improve them,
please https://github.com/reactor/.github/blob/master/CONTRIBUTING.md[get involved].

== Where to Go from Here
* Head to <<getting-started>> if you feel like jumping straight into the code.
* If you are new to reactive programming, though, you should probably start with the
<<intro-reactive>>.
* If you are familiar with Reactor concepts and are just looking for the right tool
for the job but cannot think of a relevant operator, try the <<which-operator>> Appendix.
* In order to dig deeper into the core features of Reactor, head to <<core-features>> to
learn:
** More about Reactor's reactive types in the <<flux>> and <<mono>>
sections.
** How to switch threading contexts using <<schedulers,a scheduler>>.
** How to handle errors in the <<error.handling>> section.
* Unit testing? Yes it is possible with the `reactor-test` project! See <<testing>>.
* <<producing>> offers a more advanced way of creating reactive sources.
* Other advanced topics are covered in <<advanced>>.
