[[context.propagation]]
= Context-Propagation Support

Since 3.5.0, Reactor-Core embeds support for the `io.micrometer:context-propagation` SPI.
This library is intended as a means to easily adapt between various implementations of the concept of a Context, of which
`ContextView`/`Context` is an example, and between `ThreadLocal` variables as well.

`ReactorContextAccessor` allows the Context-Propagation library to understand Reactor `Context` and `Contextview`.
It implements the SPI and is loaded via `java.util.ServiceLoader`.
No user action is required, other than having a dependency on both reactor-core and `io.micrometer:context-propagation`. The `ReactorContextAccessor` class is public but shouldn't generally be accessed by user code.

On top of that, Reactor-Core 3.5.0 also modifies the behavior of a couple key operators as well as introduces the `contextCapture` operator
to transparently deal with `ContextSnapshot`s if the library is available at runtime.

== `contextCapture` Operator
This operator can be used when one needs to capture `ThreadLocal` value(s) at subscription time and reflect these values in the Reactor `Context` for the benefit of upstream operators.
It relies on the `context-propagation` library and notably the registered `ThreadLocalAccessor`(s) to discover relevant ThreadLocal values.

This is a convenient alternative to `contextWrite` which uses the `context-propagation` API to obtain a `ContextSnapshot` and then uses that snapshot to populate the Reactor `Context`.

As a result, if there were any ThreadLocal values during subscription phase, for which there is a registered `ThreadLocalAccessor`, their values would now be stored in the Reactor `Context` and visible
at runtime in upstream operators.

====
[source,java]
----
//assuming TL is known to Context-Propagation as key TLKEY.
static final ThreadLocal<String> TL = new ThreadLocal<>();

//in the main thread, TL is set to "HELLO"
TL.set("HELLO");

Mono.deferContextual(ctx ->
  Mono.delay(Duration.ofSeconds(1))
      //we're now in another thread, TL is not set
      .map(v -> "delayed ctx[" + TLKEY + "]=" + ctx.getOrDefault(TLKEY, "not found") + ", TL=" + TL.get())
)
.contextCapture()
.block(); // returns "delayed ctx[TLKEY]=HELLO, TL=null"
----
====

== Operators that transparently restore a snapshot: `handle` and `tap`
Both `Flux` and `Mono` variants of `handle` and `tap` will have their behavior slightly modified
if the Context-Propagation library is available at runtime.

Namely, if their downstream `ContextView` is not empty they will assume a context capture has occurred
(either manually or via the `contextCapture()` operator) and will attempt to restore `ThreadLocal`s from
that snapshot transparently.

These operators will ensure restoration is performed around the user-provided code, respectively:
 - `handle` will wrap the `BiConsumer` in one which restores `ThreadLocal`s
 - `tap` variants will wrap the `SignalListener` into one that has the same kind of wrapping around each method (this includes the `addToContext` method)

The intent is to have a minimalistic set of operators transparently perform restoration.
As a result we chose operators with rather general and broad applications (one with transformative capabilities, one with side-effect capabilities)

====
[source,java]
----
//assuming TL is known to Context-Propagation.
static final ThreadLocal<String> TL = new ThreadLocal<>();

//in the main thread, TL is set to "HELLO"
TL.set("HELLO");

Mono.delay(Duration.ofSeconds(1))
  //we're now in another thread, TL is not set yet
  .doOnNext(v -> System.out.println(TL.get()))
  //inside the handler however, TL _is_ restored
  .handle((v, sink) -> sink.next("handled delayed TL=" + TL.get()))
  .contextCapture()
  .block(); // prints "null" and returns "handled delayed TL=HELLO"
----
====