[[reactor-extra]]
= Reactor-Extra

The `reactor-extra` artifact contains additional operators and utilities that are for
users of `reactor-core` with advanced needs.

As this is a separate artifact, you need to explicitly add it to your build:

[source,groovy]
----
dependencies {
     compile 'io.projectreactor:reactor-core'
     compile 'io.projectreactor.addons:reactor-extra' <1>
}
----
<1> Add the reactor extra artifact in addition to core. See <<getting>> for details
about why you don't need to specify a version if you use the BOM, usage in Maven, etc...

[[extra-tuples]]
== `TupleUtils` and Functional Interfaces

The `reactor.function` package contains functional interfaces that complement the Java 8
`Function`, `Predicate` and `Consumer` interfaces, for 3 to 8 values.

`TupleUtils` offers static methods that act as a bridge between lambdas of these functional
interfaces to a similar interface on the corresponding `Tuple`.

This allows to easily work with independent parts of any `Tuple`, for instance:

[source,java]
----
.map(tuple -> {
  String firstName = tuple.getT1();
  String lastName = tuple.getT2();
  String address = tuple.getT3();

  return new Customer(firstName, lastName, address);
});
----
Can be instead written as

[source,java]
----
.map(TupleUtils.function(Customer::new)); // <1>
----
<1> (as `Customer` constructor conforms to `Consumer3` functional interface signature)

[[extra-math]]
== Math Operators With `MathFlux`

The `reactor.math` package contains a `MathFlux` specialized version of `Flux` that offers
mathematical operators, like `max`, `min`, `sumInt`, `averageDouble`...

[[extra-repeat-retry]]
== Repeat and Retry Utilities

The `reactor.retry` package contains utilities to help in writing `Flux#repeatWhen` and
`Flux#retryWhen` functions. The entry points are factory methods in respectively `Repeat`
and `Retry` interfaces.

Both interfaces can be used as a mutative builder AND are implementing the correct
`Function` signature to be used in their counterpart operators.

Since 3.2.0, one of the most advanced retry strategies offered by these utilities is
also part of the `reactor-core` main artifact directly: exponential backoff is
available as the `Flux#retryBackoff` operator.


[[extra-schedulers]]
== Schedulers

Reactor-extra comes with several specialized schedulers:

 - `ForkJoinPoolScheduler` in package `reactor.scheduler.forkjoin`: uses the Java `ForkJoinPool` to execute tasks.
 - `SwingScheduler` in package `reactor.swing` executes tasks in the Swing UI event loop thread, the `EDT`.
 - `SwtScheduler` in package `reactor.swing` executes tasks in the SWT UI event loop thread.
