[[getting-started]]
= Getting Started

This section contains information that should help you get going with Reactor. It
includes the following sections:

* <<getting-started-introducing-reactor>>
* <<prerequisites>>
* <<getting-started-understanding-bom>>
* <<getting>>

[[getting-started-introducing-reactor]]
== Introducing Reactor

//TODO flesh out, reword. could also be updated on the website
Reactor is a fully non-blocking reactive programming foundation for the JVM, with
efficient demand management (in the form of managing "`backpressure`"). It integrates
directly with the Java 8 functional APIs, notably `CompletableFuture`, `Stream`, and
`Duration`. It offers composable asynchronous sequence APIs -- `Flux` (for [N] elements) and
`Mono` (for [0|1] elements) -- and extensively implements the
https://www.reactive-streams.org/[Reactive Streams] specification.

Reactor also supports non-blocking inter-process communication with the
`reactor-netty` project. Suited for Microservices Architecture, Reactor Netty offers
backpressure-ready network engines for HTTP (including Websockets), TCP, and UDP.
Reactive encoding and decoding are fully supported.

[[prerequisites]]
== Prerequisites

Reactor Core runs on `Java 8` and above.

It has a transitive dependency on `org.reactivestreams:reactive-streams:1.0.3`.

[NOTE]
.Android Support
====
* Reactor 3 does not officially support or target Android (consider using RxJava 2 if
such support is a strong requirement).
* However, it should work fine with Android SDK 26 (Android O) and above.
* It will likely work fine with Android SDK 21 (Android 5.0) and above when desugaring 
is enabled. See https://developer.android.com/studio/write/java8-support#library-desugaring
* We are open to evaluating changes that benefit Android support in a best-effort
fashion. However, we cannot make guarantees. Each decision must be made on a
case-by-case basis.
====

[[getting-started-understanding-bom]]
== Understanding the BOM and versioning scheme

Reactor 3 uses a BOM (Bill of Materials) model (since `reactor-core 3.0.4`, with the `Aluminium` release train).
This curated list groups artifacts that are meant to work well together, providing
the relevant versions despite potentially divergent versioning schemes in these artifacts.

Note the versioning scheme has changed between 3.3.x and 3.4.x (Dysprosium and Europium).

Artifacts follow a versioning scheme of `MAJOR.MINOR.PATCH-QUALIFIER` while the BOM is versioned using a CalVer inspired scheme of `YYYY.MINOR.PATCH-QUALIFIER`, where:

 * `MAJOR` is the current generation of Reactor, where each new generation can bring fundamental changes to the structure of the project (which might imply a more significant migration effort)
 * `YYYY` is the year of the first GA release in a given release cycle (like 3.4.0 for 3.4.x)
 * `.MINOR` is a 0-based number incrementing with each new release cycle
 ** in the case of projects, it generally reflects wider changes and can indicate a moderate migration effort
 ** in the case of the BOM it allows discerning between release cycles in case two get first released the same year
 * `.PATCH` is a 0-based number incrementing with each service release
 * `-QUALIFIER` is a textual qualifier, which is omitted in the case of GA releases (see below)

The first release cycle to follow that convention is thus `2020.0.x`, codename `Europium`.
The scheme uses the following qualifiers (note the use of dash separator), in order:

 * `-M1`..`-M9`: milestones (we don't expect more than 9 per service release)
 * `-RC1`..`-RC9`: release candidates (we don't expect more than 9 per service release)
 * `-SNAPSHOT`: snapshots
 * _no qualifier_ for GA releases

NOTE: snapshots appear higher in the order above because, conceptually, they're always "the freshest pre-release" of any given PATCH.
Even though the first deployed artifact of a PATCH cycle will always be a -SNAPSHOT, a similarly named but more up-to-date snapshot
would also get released after eg. a milestone or between release candidates.

Each release cycle is also given a codename, in continuity with the previous codename-based
scheme, which can be used to reference it more informally (like in discussions, blog posts, etc...).
The codenames represent what would traditionally be the MAJOR.MINOR number. They (mostly)
come from the https://en.wikipedia.org/wiki/Periodic_table#Overview[Periodic Table of
Elements], in increasing alphabetical order.

NOTE: Up until Dysprosium, the BOM was versioned using a release train scheme with a codename followed by a qualifier, and the qualifiers were slightly different.
For example: Aluminium-RELEASE (first GA release, would now be something like YYYY.0.0), Bismuth-M1, Californium-SR1 (service release
would now be something like YYYY.0.1), Dysprosium-RC1, Dysprosium-BUILD-SNAPSHOT (after each patch, we'd go back to the same snapshot version. would now be something
like YYYY.0.X-SNAPSHOT so we get 1 snapshot per PATCH)

[[getting]]
== Getting Reactor

As <<getting-started-understanding-bom,mentioned earlier>>, the easiest way to use Reactor in your core is to use the BOM and
add the relevant dependencies to your project. Note that, when you add such a dependency,
you must omit the version so that the version gets picked up from the BOM.

However, if you want to force the use of a specific artifact's version, you can specify
it when adding your dependency, as you usually would. You can also forgo the BOM entirely
and specify dependencies by their artifact versions.

WARNING: As of this version (reactor-core {project-version}), the latest stable BOM in the associated
release train line is `{reactorReleaseTrain}`, which is what is used in snippets below.
There might be newer versions since then (including snapshots, milestones and new release train lines),
see https://projectreactor.io/docs for the latest artifacts and BOMs.

=== Maven Installation

Maven natively supports the BOM concept. First, you need to import the BOM by
adding the following snippet to your `pom.xml`:

====
[source,xml,subs=attributes+]
----
<dependencyManagement> <1>
    <dependencies>
        <dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-bom</artifactId>
            <version>{reactorReleaseTrain}</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
----
<1> Notice the `dependencyManagement` tag. This is in addition to the regular
`dependencies` section.
====

If the top section (`dependencyManagement`) already exists in your pom, add only the contents.

Next, add your dependencies to the relevant reactor projects, as usual, except without a
`<version>`, as follows:

====
[source,xml]
----
<dependencies>
    <dependency>
        <groupId>io.projectreactor</groupId>
        <artifactId>reactor-core</artifactId> <1>
        <2>
    </dependency>
    <dependency>
        <groupId>io.projectreactor</groupId>
        <artifactId>reactor-test</artifactId> <3>
        <scope>test</scope>
    </dependency>
</dependencies>
----
<1> Dependency on the core library.
<2> No version tag here.
<3> `reactor-test` provides facilities to unit test reactive streams.
====

=== Gradle Installation

Prior to version 5.0, Gradle has no core support for Maven BOMs, but you can use Spring's
https://github.com/spring-gradle-plugins/dependency-management-plugin[gradle-dependency-management]
plugin.

First, apply the plugin from the Gradle Plugin Portal, as follows:

====
[source,groovy]
----
plugins {
    id "io.spring.dependency-management" version "1.0.7.RELEASE" <1>
}
----
<1> as of this writing, 1.0.7.RELEASE is the latest version of the plugin.
Check for updates.
====

Then use it to import the BOM, as follows:

====
[source,groovy,subs=attributes+]
----
dependencyManagement {
     imports {
          mavenBom "io.projectreactor:reactor-bom:{reactorReleaseTrain}"
     }
}
----
====

Finally add a dependency to your project, without a version number, as follows:

====
[source,groovy]
----
dependencies {
     implementation 'io.projectreactor:reactor-core' <1>
}
----
<1> There is no third `:` separated section for the version. It is taken from
the BOM.
====

Since Gradle 5.0, you can use the native Gradle support for BOMs:

====
[source,groovy,subs=attributes+]
----
dependencies {
     implementation platform('io.projectreactor:reactor-bom:{reactorReleaseTrain}')
     implementation 'io.projectreactor:reactor-core' <1>
}
----
<1> There is no third `:` separated section for the version. It is taken from
the BOM.
====


=== Milestones and Snapshots

Milestones and developer previews are distributed through the Spring Milestones
repository rather than Maven Central. To add it to your build configuration
file, use the following snippet:

.Milestones in Maven
====
[source,xml]
----
<repositories>
	<repository>
		<id>spring-milestones</id>
		<name>Spring Milestones Repository</name>
		<url>https://repo.spring.io/milestone</url>
	</repository>
</repositories>
----
====

For Gradle, use the following snippet:

.Milestones in Gradle
====
[source,groovy]
----
repositories {
  maven { url 'https://repo.spring.io/milestone' }
  mavenCentral()
}
----
====

Similarly, snapshots are also available in a separate dedicated repository, as the following example show:

.-SNAPSHOTs in Maven
====
[source,xml]
----
<repositories>
	<repository>
		<id>spring-snapshots</id>
		<name>Spring Snapshot Repository</name>
		<url>https://repo.spring.io/snapshot</url>
	</repository>
</repositories>
----
====

.-SNAPSHOTs in Gradle
====
[source,groovy]
----
repositories {
  maven { url 'https://repo.spring.io/snapshot' }
  mavenCentral()
}
----
====

[[support]]
== Support and policies

The entries below are mirroring https://github.com/reactor/.github/blob/master/SUPPORT.adoc

include::https://raw.githubusercontent.com/reactor/.github/master/SUPPORT.adoc[leveloffset=3]
