[[kotlin]]
= Kotlin support

[[kotlin-introduction]]
https://kotlinlang.org[Kotlin] is a statically-typed language targeting the JVM (and other platforms),
which allows writing concise and elegant code while providing very good
https://kotlinlang.org/docs/reference/java-interop.html[interoperability] with
existing libraries written in Java.

This section describes Reactor's support for Kotlin.

[[kotlin-requirements]]
== Requirements

Reactor supports Kotlin 1.1+ and requires
https://bintray.com/bintray/jcenter/org.jetbrains.kotlin%3Akotlin-stdlib[`kotlin-stdlib`]
(or one of its https://bintray.com/bintray/jcenter/org.jetbrains.kotlin%3Akotlin-stdlib-jre7[`kotlin-stdlib-jre7`]
or https://bintray.com/bintray/jcenter/org.jetbrains.kotlin%3Akotlin-stdlib-jre8[`kotlin-stdlib-jre8`] variants).

[[kotlin-extensions]]
== Extensions

[WARNING]
=====
As of `Dysprosium-M1` (ie. `reactor-core 3.3.0.M1`), Kotlin extensions are moved to a
dedicated https://github.com/reactor/reactor-kotlin-extensions[`reactor-kotlin-extensions`]
module with new package names that start with `reactor.kotlin` instead of simply `reactor`.

As a consequence, Kotlin extensions in `reactor-core` module are deprecated.
The new dependency's groupId and artifactId are:

====
[source,gradle]
----
io.projectreactor.kotlin:reactor-kotlin-extensions
----
====
=====

Thanks to its great https://kotlinlang.org/docs/reference/java-interop.html[Java interoperability]
and to https://kotlinlang.org/docs/reference/extensions.html[Kotlin extensions], Reactor
Kotlin APIs leverage regular Java APIs and are additionally enhanced by a few Kotlin-specific APIs
that are available out of the box within Reactor artifacts.

NOTE: Keep in mind that Kotlin extensions need to be imported to be used. This means
for example that the `Throwable.toFlux` Kotlin extension
is available only if `import reactor.kotlin.core.publisher.toFlux` is imported.
That said, similar to static imports, an IDE should automatically suggest the import in most cases.

For example, https://kotlinlang.org/docs/reference/inline-functions.html#reified-type-parameters[Kotlin reified type parameters]
provide a workaround for JVM https://docs.oracle.com/javase/tutorial/java/generics/erasure.html[generics type erasure],
and Reactor provides some extensions to take advantage of this feature.

The following table compares Reactor with Java against Reactor with Kotlin and extensions:

|===
|*Java*|*Kotlin with extensions*
|`Mono.just("foo")`
|`"foo".toMono()`
|`Flux.fromIterable(list)`
|`list.toFlux()`
|`Mono.error(new RuntimeException())`
|`RuntimeException().toMono()`
|`Flux.error(new RuntimeException())`
|`RuntimeException().toFlux()`
|`flux.ofType(Foo.class)`
|`flux.ofType<Foo>()` or `flux.ofType(Foo::class)`
|`StepVerifier.create(flux).verifyComplete()`
|`flux.test().verifyComplete()`
|===

The https://projectreactor.io/docs/kotlin/release/kdoc-api/[Reactor KDoc API] lists and documents
all the available Kotlin extensions.

[[kotlin-null-safety]]
== Null Safety

One of Kotlin's key features is https://kotlinlang.org/docs/reference/null-safety.html[null safety],
which cleanly deals with `null` values at compile time rather than bumping into the famous
`NullPointerException` at runtime. This makes applications safer through nullability
declarations and expressive "`value or no value`" semantics without paying the cost of wrappers such as `Optional`.
(Kotlin allows using functional constructs with nullable values. See this
https://www.baeldung.com/kotlin-null-safety[comprehensive guide to Kotlin null-safety].)

Although Java does not let one express null safety in its type-system, Reactor <<null-safety,now
provides null safety>> of the whole Reactor API through tooling-friendly annotations declared
in the `reactor.util.annotation` package.
By default, types from Java APIs used in Kotlin are recognized as
https://kotlinlang.org/docs/reference/java-interop.html#null-safety-and-platform-types[platform types]
for which null-checks are relaxed.
https://github.com/Kotlin/KEEP/blob/jsr-305/proposals/jsr-305-custom-nullability-qualifiers.md[Kotlin support for JSR 305 annotations]
and Reactor nullability annotations provide null-safety for the whole Reactor API to Kotlin developers,
with the advantage of dealing with `null`-related issues at compile time.

You can configure the JSR 305 checks by adding the `-Xjsr305` compiler flag with the following
options: `-Xjsr305={strict|warn|ignore}`.

For kotlin versions 1.1.50+, the default behavior is the same as `-Xjsr305=warn`.
The `strict` value is required to have the Reactor API full null-safety taken into account
but should be considered experimental, since the Reactor API nullability declaration could evolve
even between minor releases, as more checks may be added in the future).

NOTE: Nullability for generic type arguments, variable arguments, and array elements is not supported yet,
but itshould be in an upcoming release. See https://github.com/Kotlin/KEEP/issues/79[this dicussion]
for up-to-date information.
