[[metrics]]
= Exposing Reactor metrics

Project Reactor is a framework designed for performance and better utilization of resources.
But, to understand the performance of your system, you have to monitor and keep an eye on various performance aspects.

This is why Reactor provides a built-in integration with https://micrometer.io[Micrometer].

== Scheduler metrics

Every async operation in Reactor is scheduled via Schedulers abstraction described in <<schedulers>>.
This is why it is important to monitor your schedulers and react accordingly when some of the key metrics start looking suspicious.

To enable Schedulers' metrics, you will need to use the following method:
====
[source,java]
----
Schedulers.enableMetrics();
----
====

WARNING: The instrumentation is performed when a scheduler is created. It is recommended to call this method as easly as possible.

TIP: If you're using Spring Boot, it is a good idea to place the invocation before `SpringApplication.run(Application.class, args)` call.

After you enable the scheduler metrics, Reactor will instrument (with Micrometer's built-in instrumentation) the underlying executors.

Please refer to http://micrometer.io/docs[Micrometer's documentation] for the exposed metrics, such as:

- executor_active_threads
- executor_completed_tasks_total
- executor_pool_size_threads
- executor_queued_tasks
- executor_secounds_{count, max, sum}

Since one scheduler may have multiple executors, every executor metric has a `reactor_scheduler_id` tag.


// TODO
// == Flow metrics