=== On Backpressure, and ways to reshape requests

When implementing backpressure in Reactor, the way consumer pressure is propagated back to the source is by sending a `request` to the upstream operator.
The sum of current requests is sometimes referenced to as the current "demand", or "pending request".
Demand is capped at `Long.MAX_VALUE`, representing an unbounded request ("produce as fast as you can", basically disabling backpressure).

The first request comes from the final subscriber, at subscription time, yet the most direct ways of subscribing all immediately trigger an unbounded request of `Long.MAX_VALUE`:

 - `subscribe()` and most of its lambda-based variants (to the exception of the one that has a Consumer<Subscription>)
 - `block()`, `blockFirst()` and `blockLast()`
 - iterating over a `toIterable()`/`toStream()`

The simplest way of customizing the original request is to `subscribe` with a `BaseSubscriber` with the `hookOnSubscribe` method overridden:

[source,java]
----
Flux.range(1, 10)
    .doOnRequest(r -> System.out.println("request of " + r))
    .subscribe(new BaseSubscriber<Integer>() {

      @Override
      public void hookOnSubscribe(Subscription subscription) {
        request(1);
      }

      @Override
      public void hookOnNext(Integer integer) {
        System.out.println("Cancelling after having received " + integer);
        cancel();
      }
    });
----

This snippets prints out:

----
request of 1
Cancelling after having received 1
----

WARNING: When manipulating a request, you must be careful to produce enough demand for
the sequence to advance or your Flux will get "stuck". That is why `BaseSubscriber`
defaults to an unbounded request in `hookOnSubscribe`. When overriding this hook, you should usually
call `request` at least once.

==== Operators changing the demand from downstream
One thing to keep in mind is that demand expressed at the subscribe level **can** be reshaped by each operator in the chain upstream.
A textbook case is the `buffer(N)` operator: if it receives a `request(2)`, it is interpreted as a demand for **two full buffers**.
As a consequence, since buffers need `N` elements to be considered full, the `buffer` operator reshapes the request to `2 x N`.

You might also have noticed that some operators have variants that take an `int` input parameter called `prefetch`.
This is another category of operators that modify the downstream request.
These are usually operators that deal with inner sequences, deriving a `Publisher` from each incoming element (like `flatMap`).

**Prefetch** is a way to tune the initial request made on these inner sequences.
If unspecified, most of these operators start with a demand of `32`.

These operators usually also implement a **replenishing optimization**: once the operator has seen 25% of the prefetch request fulfilled, it re-requests 25% from upstream.
This is a heuristic optimization made so that these operators proactively anticipate the upcoming requests.

Finally, a couple of operators are made to directly let you tune the request: `limitRate` and `limitRequest`.

`limitRate(N)` splits the downstream requests so that they are propagated upstream in smaller batches.
For instance, a request of `100` made to `limitRate(10)` would result in _at most_ `10` requests of `10` being propagated to the upstream.
Note that in this form `limitRate` actually implements the replenishing optimization discussed above.

The operator has a variant that also lets you tune the replenishing amount, referred to as the `lowTide` in the variant: `limitRate(highTide, lowTide)`.
Choosing a `lowTide` of `0` will result in **strict** batches of `highTide` requests, instead of batches further reworked by the replenishing strategy.

`limitRequest(N)` on the other hand **caps** the downstream request to a maximum total demand.
It adds up requests up to `N`. If a single `request` doesn't make the total demand overflow over `N`, that particular request is wholly propagated upstream. 
After that amount has been emitted by the source, `limitRequest` will consider the sequence complete and send an `onComplete` signal downstream and cancel the source.

