name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
filter-by-commitish: true
categories:
  - title: ':warning: Update considerations and deprecations'
    labels:
      - 'warn/api-change'
      - 'warn/behavior-change'
      - 'warn/blocker'
      - 'warn/deprecation'
      - 'warn/regression'
  - title: ':sparkles: New features and improvements'
    label: 'type/enhancement'
  - title: ':lady_beetle: Bug fixes'
    label: 'type/bug'
  - title: ':book: Documentation, Tests and Build'
    labels:
      - 'type/chores'
      - 'type/documentation'
  - title: ':up: Dependency Upgrades'
    label: 'type/dependency-upgrade'
change-template: '- $TITLE'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
exclude-contributors:
  - 'simonbasle'
  - 'OlegDokuka'
  - 'violetagg'
  - 'pderop'
  # - 'garyrussel'
  # - 'acogoluegnes'
template: |
  # :checklist: TODO below
   - [ ] Replace release train references
   - [ ] Replace older maintenance train references
   - [ ] Ensure changes from other maintenance release are indeed grouped and extra-indented
  
  ${{ github.event.repository.name }} `$RESOLVED_VERSION` is part of **`2020.0.{SR}` Release Train (`Europium` SR{SR})**.
  
  This release contains {SHORT DESCRIPTION OF THE CONTENTS}.
  
  All changes from [`{OLDER_TRAIN}`](https://github.com/${{ github.repository }}/releases/tag/v{OLDER_TRAIN}) are also included and these are listed below with an additional level of indentation.
  
  $CHANGES
  
  ## :+1: Thanks to all contributors who participated to this release
  $CONTRIBUTORS