changelog:
  exclude:
    labels:
      - ignore-changelog
      - type/test
      - type/test/flaky
      - type/chores
      - type/dependency-upgrade
  categories:
    - title: ":warning: Update considerations and deprecations"
      labels:
        - "warn/api-change"
        - "warn/behavior-change"
        - "warn/blocker"
        - "warn/deprecation"
        - "warn/regression"
    - title: ":sparkles: New features and improvements"
      labels:
        - "type/enhancement"
    - title: ":lady_beetle: Bug fixes"
      labels:
        - "type/bug"
    - title: ":book: Documentation"
      labels:
        - "type/documentation"
    - title: ":question: Other Changes"
      labels:
        - "*"
