= Debugging Reactor
Switching from an imperative and synchronous programming paradigm to a reactive
and asynchronous one can sometimes be daunting. One of the steepest steps in the
learning curve is how to analyze and debug when something goes wrong.

In the imperative world, this is usually pretty straightforward nowadays: just
read the stacktrace and you'll spot where the problem originated, and more: was
it entirely a failure of your code? Did the failure occur in some library code?
If so, what part of your code called the library, potentially passing in
improper parameters that ultimately caused the failure? (I'm looking at you,
`null`!)

== The typical Reactor stack trace
But as soon as you shift to asynchronous code, things can get much more
complicated...

Consider the following stacktrace:

.A typically scary Reactor stacktrace
[source]
----
java.lang.IndexOutOfBoundsException: Source emitted more than one item
	at reactor.core.publisher.MonoSingle$SingleSubscriber.onNext(MonoSingle.java:120)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.emitScalar(FluxFlatMap.java:380)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:349)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:119)
	at reactor.core.publisher.FluxRange$RangeSubscription.slowPath(FluxRange.java:144)
	at reactor.core.publisher.FluxRange$RangeSubscription.request(FluxRange.java:99)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:172)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:316)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:94)
	at reactor.core.publisher.FluxRange.subscribe(FluxRange.java:68)
	at reactor.core.publisher.FluxMapFuseable.subscribe(FluxMapFuseable.java:67)
	at reactor.core.publisher.FluxFlatMap.subscribe(FluxFlatMap.java:98)
	at reactor.core.publisher.MonoSingle.subscribe(MonoSingle.java:58)
	at reactor.core.publisher.Mono.subscribeWith(Mono.java:2668)
	at reactor.core.publisher.Mono.subscribe(Mono.java:2629)
	at reactor.core.publisher.Mono.subscribe(Mono.java:2604)
	at reactor.core.publisher.Mono.subscribe(Mono.java:2582)
	at reactor.guide.GuideTests.debuggingCommonStacktrace(GuideTests.java:722)
----

There is a lot going on there! We get an `IndexOutOfBoundsException` which tell
us that a "*source emitted* _more than one item_".

We can probably quickly come to assume that this source is a Flux/Mono, as
confirmed by the line below that mentions `MonoSingle`. So it appears to be some
sort of complaint from a `single` operator.

Referring to the javadoc for `Mono#single` operator, we indeed remember that
`single` has a contract: the source must emit exactly one element. It appears
we had a source that emitted more than one and thus violated that contract.

Can we dig deeper and identify that source? The following rows don't seem very
helpful. They take us on a travel inside the internals of what seems to be a
reactive chain, through `subscribes` and `requests`...

By skimming over these rows, we can at least start to form a picture of the kind
of chain that went wrong: it seems to involve a `MonoSingle`, a `FluxFlatMap`
and a `FluxRange` (each get several rows in the trace, but overall these 3
classes are involved). So a `range().flatMap().single()` chain maybe?

But what if we use that pattern a lot in our application? This still doesn't
tell us much, and simply searching for `single` isn't going to cut it. Then the
last line refers to some of our code. Finally!

Hold on... When we go to the source file, all we see is that a pre-existing
`Flux` is subscribed to:
[source,java]
----
toDebug.subscribe(System.out::println, Throwable::printStackTrace);
----

All of this happened at subscription time, but the `Flux` itself wasn't
_declared_ there. Worse, when we go to where the variable is declared, we see:
[source,java]
----
public Mono<String> toDebug; //please overlook the public class attribute :p
----

The variable isn't even _instantiated_ where it is declared. Let's assume a
worst case scenario where we find out there could be a few different codepath
that set it in the application... So we're still unsure of which one caused the
issue.

NOTE: This is kind of the Reactor equivalent of a runtime error, as opposed to a
compilation error.

What we want to find out more easily is where the operator was added into the
chain, where the `Flux` was declared. We usually refer to that as the *assembly*
of the Flux.

== Activating debug mode
Even though the stacktrace was still able to convey some information for someone
with a bit of experience, we can see that it is not ideal by itself in more
advanced cases.

Fortunately, Reactor comes with a debugging-oriented capability of
*assembly-time instrumentation*.

This is done by customizing the `Hook.onOperator` hook *at application start*
(or at least before the incriminated flux or mono can be instantiated), like so:
[source,java]
----
Hooks.onOperator(providedHook -> providedHook.operatorStacktrace());
----

The idea is that this will start instrumenting the calls to `Flux` (and
`Mono`)'s operator methods (where they are assembled into the chain) by wrapping
the construction of the operator and capturing a stacktrace there. Since this is
done when the operator chain is declared, the hook should be activate *before*
that, so the safest way is to activate it right at the start of your
application.

Later on, if an exception occurs, the failing operator will be able to refer
to that capture and append it to the stacktrace.

In the next section, we'll see how the stacktrace differs and how to interpret
that new information.

== Reading a stack trace in debug mode
Reusing our initial example but activating the `operatorStacktrace` debug
feature, here is the stack we now get:

[source]
----
java.lang.IndexOutOfBoundsException: Source emitted more than one item
	at reactor.core.publisher.MonoSingle$SingleSubscriber.onNext(MonoSingle.java:120)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:314) <1>
...
<2>
...
	at reactor.core.publisher.Mono.subscribeWith(Mono.java:2668)
	at reactor.core.publisher.Mono.subscribe(Mono.java:2629)
	at reactor.core.publisher.Mono.subscribe(Mono.java:2604)
	at reactor.core.publisher.Mono.subscribe(Mono.java:2582)
	at reactor.guide.GuideTests.debuggingActivated(GuideTests.java:727)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: <3>
Assembly trace from producer [reactor.core.publisher.MonoSingle] : <4>
	reactor.core.publisher.Flux.single(Flux.java:5335)
	reactor.guide.GuideTests.scatterAndGather(GuideTests.java:689)
	reactor.guide.GuideTests.populateDebug(GuideTests.java:702)
	org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	org.junit.rules.RunRules.evaluate(RunRules.java:20)
Error has been observed by the following operator(s): <5>
	|_	Flux.single(TestWatcher.java:55) <6>
----
<1> This is new: what we see here is the wrapper operator that captures the
stack.
<2> Apart from that, the first section of the stacktrace is still the same for
the most part,showing a bit of operators internals (so we removed a bit of the
snippet here)
<3> This is where the new stuff from debugging mode starts appearing.
<4> First we get some details on where the operator was assembled, hurray!
<5> We also get a traceback of the error as it propagated through the operator
chain, from first to last (error site to subscribe site).
<6> Each operator that saw the error is mentioned along with the class and line
where it originated. If an operator is assembled from within Reactor code, the
later would be omitted.

As you can see, the captured stacktrace is appended to the original error as a
suppressed `OnAssemblyException`. There are two parts to it, but the first
section is the most interesting. It shows the path of construction for the
operator that triggered the exception. Here it shows that the `single` that
caused our issue was created in the `scatterAndGather` method, itself called
from a `populateDebug` method that got executed through JUnit.

We are now armed with enough information to find the culprit, let's have a look
at that `scatterAndGather` method:
[source,java]
----
private Mono<String> scatterAndGather(Flux<String> urls) {
    return urls.flatMap(url -> doRequest(url))
           .single(); <1>
}
----
<1> Sure enough, here is our `single`.

Now we can see what the root cause of the error was: a `flatMap` that performs
several HTTP calls to a few urls is chained with `single`, which seem a bit too
restrictive. After a short `git blame` and a quick discussion with the author of
that line, we find out he meant to use the less restrictive `take(1)` instead...

Congratulations, *we solved our problem*!

[quote]
Error has been observed by the following operator(s):

That second part of the debug stacktrace was not necessarily very interesting in
this particular example, because the error was actually happening in the last
operator in the chain (the one closest to `subscribe`). Taking another example
might make it clearer:
[source,java]
----
FakeRepository.findAllUserByName(Flux.just("pedro", "simon", "stephane"))
              .transform(FakeUtils1.applyFilters)
              .transform(FakeUtils2.enrichUser)
              .blockLast();
----

Now imagine that inside `findAllUserByName` there is a `map` that fails. Here we
would see the following final traceback:
[source,java]
----
Error has been observed by the following operator(s):
	|_	Flux.map(FakeRepository.java:27)
	|_	Flux.map(FakeRepository.java:28)
	|_	Flux.filter(FakeUtils1.java:29)
	|_	Flux.transform(GuideDebuggingExtraTests.java:41)
	|_	Flux.elapsed(FakeUtils2.java:30)
	|_	Flux.transform(GuideDebuggingExtraTests.java:42)
----

This correspond to a flattened out version of the chain of operators, or rather
of the section of the chain that gets notified of the error:

 1. the exception originates in the first `map`
 2. it is seen by a second `map` (both in fact correspond to the
    `findAllUserByName` method)
 3. then it is seen by a `filter` and a `transform`, which indicates us that part of
    the chain is constructed via a reusable transformation function (here, the
    `applyFilters` utility method).
 4. finally it is seen by an `elapsed` and a `transform`. Once again, elapsed is
    what is applied by the transformation function of that second transform.

=== Cost of debug mode
We are dealing with a form of instrumentation here, and creating a
stacktrace is costly. That is why this debugging feature should only be
activated in a controlled manner, as a last resort.
There are ways of limiting the impact of that feature by restricting the hook to
the type of operator that is causing an issue.

The filter to use is best determined by looking at the class in the stack trace,
after removing any `Parallel`, `Flux` and `Mono` prefixes and the `Fuseable`
suffix. For instance in our case:

----
at reactor.core.publisher.MonoSingle$SingleSubscriber.onNext(MonoSingle.java:120)
----

We have `MonoSingle.java:120`, so `MonoSingle` operator implementation and
`single` as the filtering keyword.

So we could only instrument uses of the incriminating operator by doing:

[source,java]
----
Hooks.onOperator(providedHook -> providedHook.ifName("single") <1>
                                             .operatorStacktrace());
----
<1> Only activate for operator classes named "single", ignoring case and the
"Parallel", "Flux" or "Mono" prefixes, as well as "Fuseable" suffix (as seen in
stacktrace)

=== The `checkpoint()` alternative
The debug mode is global and affects every single operator assembled into a
`Flux` or `Mono` inside the application. This has the benefit of allowing
*after the fact debugging*: whatever the error, we will obtain additional info
to debug it.

As we saw in the "Cost of debug mode" above, this is at the cost of an impact on
performance (due to the number of populated stacktraces). That cost can be
reduced if we have an idea of likely problematic operators. But usually this
isn't known unless we observed an error in the wild, saw we were missing
assembly information and then modified the code to activate assembly tracking,
hoping we can observe the same error again...

In that scenario, we have to switch into debugging gear and make preparations
in order to better observe a second occurrence of the error, this time capturing
all the additional information.

If you can identify reactive chains that you assemble in your application for
which serviceability is critical, *a mix of both world can be achieved with the
`checkpoint()` operator.*

You can chain this operator towards their end. The `checkpoint` operator will
work like the hook version, but only for its link of that particular chain.

There is also a `checkpoint(String)` variant that allows you to add a
description to the assembly traceback. It could for example be a static
identifier or user-readable description, or a wider *correlation ID* coming from
a header in the case of an HTTP request for instance...

That information appears in the first line of the traceback:

----
Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Assembly trace from producer [reactor.core.publisher.ParallelSource], described as [fooCorrelation1234] : <1>
	reactor.core.publisher.ParallelFlux.checkpoint(ParallelFlux.java:174)
	reactor.core.publisher.FluxOnAssemblyTest.parallelFluxCheckpointDescription(FluxOnAssemblyTest.java:159)
Error has been observed by the following operator(s):
	|_	ParallelFlux.checkpointnull
----
<1> `fooCorrelation1234` is the description provided in `checkpoint`

Last but not least, the checkpoint can also be made in a lightweight manner: using a unique
enough description, the stack trace filling in omitted when using `checkpointLight(String)`.
The traceback changes to only contain one line:

----
...
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Assembly site of producer [reactor.core.publisher.FluxElapsed] is identified by light checkpoint [light checkpoint identifier].
----

Note that When both global debugging and local `checkpoint()` are enabled, checkpointed snapshot
stacks will be appended as suppressed error after the observing operator graph and
following the same declarative order.

== Logging a stream
Additionally to stacktrace debugging and analysis, another powerful tool to have
in your toolbelt is the capability to trace and log events in an asynchronous
sequence.

The `log()` operator can do just that. Chained inside a sequence, it will peek
at every event of the Flux/Mono upstream of it (including `onNext`, `onError`
and `onComplete` of course, but also _subscriptions_, _cancellation_ and
_requests_).

The operator picks up common logging frameworks like Log4J and Logback through
*SLF4J*, and will default to the JDK Logger in case none can be found.

For instance, supposing we have _logback_ activated and configured, and a chain
like `range(1,10).take(3)`. By placing a `log()` just before the _take_, we can
get some insight as to how it works and what kind of events it propagates
upstream to the _range_:
[source,java]
----
Flux<Integer> flux = Flux.range(1, 10)
                         .log()
                         .take(3);
flux.subscribe();
----

This prints out (through the logger's console appender):
----
10:45:20.200 [main] INFO  reactor.Flux.Range.1 - | onSubscribe([Synchronous Fuseable] FluxRange.RangeSubscription) <1>
10:45:20.205 [main] INFO  reactor.Flux.Range.1 - | request(unbounded) <2>
10:45:20.205 [main] INFO  reactor.Flux.Range.1 - | onNext(1) <3>
10:45:20.205 [main] INFO  reactor.Flux.Range.1 - | onNext(2)
10:45:20.205 [main] INFO  reactor.Flux.Range.1 - | onNext(3)
10:45:20.205 [main] INFO  reactor.Flux.Range.1 - | cancel() <4>
----

Here, additionally to the logger's own formatter (time, thread, level, message),
the `log()` operator outputs a few things in its own format:

 * `reactor.Flux.Range.1` is an automatic _category_ for the log, in case you
 use the operator several times in a chain. It allows you to distinguish which
 operator's events are being logged (here, the `range`). This can be overwritten
 with your own custom category using the `log(String)` signature.
 * After the few separating characters, the actual event gets printed: here we
 get `onSubscribe`, `request`, 3 `onNext` and a `cancel`...
 * For the first line, `onSubscribe`, we get the implementation of the
 `Subscriber`, that usually correspond to the operator-specific implementation.
 Between square brackets, we get additional information if the operator can be
 automatically optimized via synchronous or asynchronous fusion (see the
 appendix on <<microfusion>>).
 * on the second line *(2)* we can see that an unbounded request was propagated
 up from downstream.
 * Then the range sends three values in a row (*(3)*)...
 * On the last line we see a cancel.

The last line *(4)* is the most interesting: we can see the `take` in action
there: it operates by cutting the sequence short after it has seen enough
elements emitted. In a word, `take` simply `cancel()` the source once it has
emitted the user-requested amount!
