== FAQ, best practices and other "How do I...?"
[[faq.chain]]
=== I just used an operator on my `Flux` but it doesn't seem to apply... What gives?

Check you have affected the result of the operator to the variable you `.subscribe()` to.

Reactor operators are decorators, they return a different instance that wraps
the source sequence and add behavior. That is why the preferred way of using
operators is to *chain* the calls.

Compare the following:

.without chaining (incorrect)
[source,java]
----
Flux<String> secrets = Flux.just("foo", "chain");
flux.map(secret -> secret.replaceAll(".", "*")); <1>
flux.subscribe(next -> System.out.println("Received: " + next));
----
<1> mistake is here

With:

.without chaining (correct)
[source,java]
----
Flux<String> secrets = Flux.just("foo", "chain");
flux = flux.map(secret -> secret.replaceAll(".", "*"));
flux.subscribe(next -> System.out.println("Received: " + next));
----
And even better:

.with chaining (best)
[source,java]
----
Flux<String> secrets = Flux
  .just("foo", "chain")
  .map(secret -> secret.replaceAll(".", "*"))
  .subscribe(next -> System.out.println("Received: " + next));
----

The first version will output:

[source]
----
Received: foo
Received: chain
----

Whereas the two other versions will output the expected:

[source]
----
Received: ***
Received: *****
----

[[faq.monoThen]]
=== My `Mono` continuation (`then` or `and`) is never called

.example
[source,java]
----
myMethod.process("a") // this method returns Mono<Void>
        .then(aVoid -> myMethod.process("b")) //this is never called
        .subscribe();
----

If the source `Mono` is either `empty` or a `Mono<Void>` (a `Mono<Void>` is
empty for all intent and purposes), some combinations will never be called. You
should expect that if there is a callback and the combination depends on the
value...

This includes the `Function` based variant of then (`then(v -> Mono.just(1))`)
and all versions of `and`.

In order to aVoid this problem and still invoke the continuation lazily, when
the source Mono terminates, use the `Supplier` based version:

[source,java]
----
myMethod.process("a")
        .then(() -> myMethod.process("b")) //executed lazily
        .subscribe();
----


//TODO reactive gems
