[[faq]]
= FAQ, Best Practices, and "How do I...?"

[[faq.wrap-blocking]]
== How do I wrap a synchronous, blocking call?

It's often the case that a source of information is synchronous and blocking.
To deal with such sources in your Reactor applications, apply the following
pattern:

[source,java]
----
Mono blockingWrapper = Mono.fromCallable(() -> { <1>
    return /* make a remote synchronous call */ <2>
});
blockingWrapper.subscribeOn(Schedulers.elastic()); <3>
----

<1> Create a new `Mono` by using `fromCallable`.
<2> Return the asynchronous, blocking resource.
<3> Subscribe with a single-threaded worker with `Schedulers.elastic()`.

You should use a Mono because the source returns one value. You should use
`Schedulers.elastic` because it creates a dedicated thread to wait for the
blocking resource without tying up some other resource.

Note that `subscribeOn` does not subscribe to the `Mono`. It specifies what 
kind of `Scheduler` to use when a subscribe call happens.

[[faq.chain]]
== I used an operator on my `Flux` but it doesn't seem to apply. What gives?

Make sure that the variable you `.subscribe()` to has been affected by the
operators you think should have been applied to it.

Reactor operators are decorators. They return a different instance that wraps
the source sequence and add behavior. That is why the preferred way of using
operators is to *chain* the calls.

Compare the following two examples:

.without chaining (incorrect)
[source,java]
----
Flux<String> flux = Flux.just("foo", "chain");
flux.map(secret -> secret.replaceAll(".", "*")); <1>
flux.subscribe(next -> System.out.println("Received: " + next));
----
<1> The mistake is here. The result isn't attached to the `flux` variable.

.without chaining (correct)
[source,java]
----
Flux<String> flux = Flux.just("foo", "chain");
flux = flux.map(secret -> secret.replaceAll(".", "*"));
flux.subscribe(next -> System.out.println("Received: " + next));
----
This sample is even better (because it's simpler):

.with chaining (best)
[source,java]
----
Flux<String> secrets = Flux
  .just("foo", "chain")
  .map(secret -> secret.replaceAll(".", "*"))
  .subscribe(next -> System.out.println("Received: " + next));
----

The first version will output:

[source]
----
Received: foo
Received: chain
----

Whereas the two other versions will output the expected:

[source]
----
Received: ***
Received: *****
----

[[faq.monoThen]]
== My `Mono` `and` is never called

.example
[source,java]
----
myMethod.process("a") // this method returns Mono<Void>
        .and(myMethod.process("b")) //this is never called
        .subscribe();
----

If the source `Mono` is either `empty` or a `Mono<Void>` (a `Mono<Void>` is
empty for all intents and purposes), some combinations will never be called.

This is the typical case for the `and` operator, which by definition needs an
element from each source to produce its output. If any of the sources are
empty, `and` produces an empty sequence as well, so be careful of its usage.
For example, using `and()` after a `then()` may cause this problem.

This is even more true of the variants of `and` that take a `Function`, meaning
that the associated Mono is chosen lazily depending on the incoming value
(which never comes in the cases of empty or `Void` sequences).

You can use `.defaultIfEmpty(T)` to replace an *empty* sequence of `T` (not a
`Void` sequence) with a default value, which could help avoid some of these
situations. Here's an example:

.use `defaultIfEmpty` before `and`
[source,java]
----
myMethod.emptySequenceForKey("a") // this method returns empty Mono<String>
        .defaultIfEmpty("") // this converts empty sequence to just the empty String
        .and(aString -> myMethod.process("b")) //this is called with the empty String
        .subscribe();
----

[[faq.retryWhen]]
== How to use `retryWhen` to emulate `retry(3)`?
The `retryWhen` operator can be quite complex. Hopefully this snippet of code
can help you understand how it works by attempting to emulate a simpler
`retry(3)`:
include::snippetRetryWhenRetry.adoc[]

[[faq.exponentialBackoff]]
== How to use `retryWhen` for exponential backoff?
Exponential backoff produces retry attempts with a growing delay between each
of the attempts, so as not to overload the source systems and risk an all out
crash. The rationale is that if the source produces an error, it is already in
an unstable state and not likely to immediately recover from it. So blindly
retrying immediately is likely to produce yet another error and add to the
instability.

Here is how to implement an exponential backoff that delays retries and increase
the delay between each attempt (pseudocode: delay = attempt number * 100 milliseconds):
[source,java]
----
Flux<String> flux =
Flux.<String>error(new IllegalArgumentException())
    .retryWhen(companion -> companion
        .doOnNext(s -> System.out.println(s + " at " + LocalTime.now())) // <1>
        .zipWith(Flux.range(1, 4), (error, index) -> { // <2>
          if (index < 4) return index;
          else throw Exceptions.propagate(error);
        })
        .flatMap(index -> Mono.delay(Duration.ofMillis(index * 100))) // <3>
        .doOnNext(s -> System.out.println("retried at " + LocalTime.now())) // <4>
    );
----
<1> We log the time of errors.
<2> We use the `retryWhen` + `zipWith` trick to propagate the error after 3
retries.
<3> Through `flatMap`, we cause a delay that depends on the attempt's index.
<4> We also log the time at which the retry happens.

When subscribed to, this fails and terminates after printing out:
----
java.lang.IllegalArgumentException at 18:02:29.338
retried at 18:02:29.459 <1>
java.lang.IllegalArgumentException at 18:02:29.460
retried at 18:02:29.663 <2>
java.lang.IllegalArgumentException at 18:02:29.663
retried at 18:02:29.964 <3>
java.lang.IllegalArgumentException at 18:02:29.964
----
<1> first retry after about 100ms
<2> second retry after about 200ms
<3> third retry after about 300ms

== How do I ensure thread affinity using `publishOn()`?

As described in <<schedulers, Schedulers>>, `publishOn()` can be used to switch
execution contexts. The `publishOn` operator influences the threading context
where the rest of the operators in the chain below it will execute, up to a new
occurrence of `publishOn`. So the placement of `publishOn` is significant.

For instance, in the example below, the `transform` function in `map()` is
executed on a worker of `scheduler1` and the `processNext` method in
`doOnNext()` is executed on a worker of `scheduler2`. Single threaded
schedulers may be used to ensure thread affinity for different stages in the
chain or for different subscribers.

[source,java]
----
EmitterProcessor<Integer> processor = EmitterProcessor.create();
processor.publishOn(scheduler1)
         .map(i -> transform(i))
         .publishOn(scheduler2)
         .doOnNext(i -> processNext(i))
         .subscribe();
----

//TODO reactive gems
