[[getting-started]]
= Getting started
== Introducing Reactor
//TODO flesh out, reword. could also be updated on the website
Reactor is a fully non-blocking reactive programming foundation for the JVM,
with efficient demand management (backpressure). It integrates directly with
Java 8 functional APIs, notably `CompletableFuture`, `Stream` and `Duration`.
It offers composable asynchronous sequence APIs `Flux` ([N] elements) and `Mono`
([0|1] elements), extensively implementing the Reactive Extensions specification.

Reactor also supports non-blocking IPC with the `reactor-ipc` components.
Suited for Microservices Architecture, Reactor IPC offers backpressure-ready
network engines for HTTP (including Websockets), TCP and UDP. Reactive Encoding/
Decoding is fully supported.

== The BOM
Reactor 3 uses a BOMfootnote:['Bill Of Materials', a curated list of versioned compatible artifacts]
model since `reactor-core 3.0.4`, with the `Aluminium` release train.

This allows to regroup artifacts that are meant to work well together without
having to wonder about the sometimes divergent versioning schemes of these artifacts.

The BOM is like a curated list of versions. It is itself versioned, using a
release train scheme with a codename followed by a qualifier:
[verse]
Aluminium-RELEASE
Carbon-BUILD-SNAPSHOT
Aluminium-SR1
Carbon-SR32footnote:[(hopefully not)]

The codenames represent what would traditionally be the MAJOR.MINOR number. They
come from the https://en.wikipedia.org/wiki/Periodic_table#Overview[Periodic Table of Elements]
(mostly), in growing alphabetical order.

The qualifiers are (in chronological order):

 * `BUILD-SNAPSHOT`
 * `M1`..`N`: Milestones or developer previews
 * `RELEASE`: The first GA release in a codename series
 * `SR1`..`N`: The subsequent GA releases in a codename series (equivalent to
   PATCH number, SR stands for "Service Release").

[[getting]]
== Getting Reactor
As mentioned above, the easiest way to use Reactor in your core is to use
the BOM and add the relevant dependencies to your project. Note that when adding
such a dependency, you omit the version so that it gets picked up from the BOM.

However, if you want to force the use of a specific artifact's version, you can
specify it when adding your dependency, as you usually would. You can also of
course forgo the BOM entirely and always specify dependencies with their artifact
versions.

=== Maven installation
The BOM concept is natively supported by Maven. First, you'll need to import the
BOM by adding the following to your `pom.xml`:footnote:[if the top section already exist in your pom, just append the contents]

[source,xml]
----
<dependencyManagement> <1>
    <dependencies>
        <dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-bom</artifactId>
            <version>Aluminium-SR1</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
----
<1> Notice the `dependencyManagement` tag, this is in addition to the regular
`dependencies` section.

Next, add your dependencies to the relevant reactor projects as usual, except
without a `<version>`:

[source,xml]
----
<dependencies>
    <dependency>
        <groupId>io.projectreactor</groupId>
        <artifactId>reactor-core</artifactId> <1>
        <2>
    </dependency>
    <dependency>
        <groupId>io.projectreactor.addons</groupId>
        <artifactId>reactor-test</artifactId> <3>
        <scope>test</scope>
    </dependency>
</dependencies>
----
<1> dependency to the core library
<2> no version tag here
<3> reactor-test provides facilities to unit test reactive streams

=== Gradle installation
Gradle has no core support for Maven BOMs, but you can use Spring's
https://github.com/spring-gradle-plugins/dependency-management-plugin[gradle-dependency-management]
plugin.

First, apply the plugin from Gradle Plugin Portal:

[source,groovy]
----
plugins {
    id "io.spring.dependency-management" version "1.0.1.RELEASE" <1>
}
----
<1> as of this writing, 1.0.1.RELEASE is the latest version of the plugin, check for updates.

Then use it to import the BOM:
[source,groovy]
----
dependencyManagement {
     imports {
          mavenBom "io.projectreactor:reactor-bom:Aluminium-SR1"
     }
}
----

Finally add a dependency to your project without a version number:
[source,groovy]
----
dependencies {
     compile 'io.projectreactor:reactor-core' <1>
}
----
<1> no third `:` separated section for the version, it is taken from the BOM
