[[kotlin]]
= Kotlin support

[[introduction]]
== Introduction

https://kotlinlang.org[Kotlin] is a statically-typed language targeting the JVM (and other platforms)
which allows writing concise and elegant code while providing a very good
https://kotlinlang.org/docs/reference/java-interop.html[interoperability] with
existing libraries written in Java.

Reactor 3.1 introduces first-class support for Kotlin which is described in this section.

[[requirements]]
== Requirements ==

Kotlin supports Kotlin 1.1+ and requires
https://bintray.com/bintray/jcenter/org.jetbrains.kotlin%3Akotlin-stdlib[`kotlin-stdlib`]
(or one of its https://bintray.com/bintray/jcenter/org.jetbrains.kotlin%3Akotlin-stdlib-jre7[`kotlin-stdlib-jre7`]
/ https://bintray.com/bintray/jcenter/org.jetbrains.kotlin%3Akotlin-stdlib-jre8[`kotlin-stdlib-jre8`] variants).

[[extensions]]
== Extensions

Thanks to its great https://kotlinlang.org/docs/reference/java-interop.html[Java interoperability]
and to https://kotlinlang.org/docs/reference/extensions.html[Kotlin extensions], Reactor
Kotlin APIs leverage regular Java APIs and are additionally enhanced by a few Kotlin specific APIs
available out of the box within Reactor artifacts.

[NOTE]
====
Keep in mind that Kotlin extensions need to be imported to be used. This means
for example that the `Throwable.toFlux` Kotlin extension
will only be available if `import reactor.core.publisher.toFlux` is imported.
That said, similar to static imports, an IDE should automatically suggest the import in most cases.
====

For example, https://kotlinlang.org/docs/reference/inline-functions.html#reified-type-parameters[Kotlin reified type parameters]
provide a workaround for JVM https://docs.oracle.com/javase/tutorial/java/generics/erasure.html[generics type erasure],
and Reactor provides some extensions to take advantage of this feature.

You can see bellow a quick comparison of Reactor with Java versus Reactor with Kotlin + extensions.

|===
|*Java*|*Kotlin with extensions*
|`Mono.just("foo")`
|`"foo".toMono()`
|`Flux.fromIterable(list)`
|`list.toFlux()`
|`Mono.error(new RuntimeException())`
|`RuntimeException().toMono()`
|`Flux.error(new RuntimeException())`
|`RuntimeException().toFlux()`
|`flux.ofType(Foo.class)`
|`flux.ofType<Foo>()` or `flux.ofType(Foo::class)`
|`StepVerifier.create(flux).verifyComplete()`
|`flux.test().verifyComplete()`
|===

https://projectreactor.io/docs/core/release/kdoc-api/[Reactor KDoc API] lists and documents
all the Kotlin extensions available.

[[null-safety]]
== Null-safety

One of Kotlin's key features is https://kotlinlang.org/docs/reference/null-safety.html[null-safety]
which cleanly deals with `null` values at compile time rather than bumping into the famous
`NullPointerException` at runtime. This makes applications safer through nullability
declarations and expressing "value or no value" semantics without paying the cost of wrappers like `Optional`.
(Kotlin allows using functional constructs with nullable values; check out this
http://www.baeldung.com/kotlin-null-safety[comprehensive guide to Kotlin null-safety].)

Although Java does not allow one to express null-safety in its type-system, Reactor now
provides null-safety of the whole Reactor API via tooling-friendly annotations declared in
the `reactor.util.annotation` package.
By default, types from Java APIs used in Kotlin are recognized as
https://kotlinlang.org/docs/reference/java-interop.html#null-safety-and-platform-types[platform types]
for which null-checks are relaxed.
https://github.com/Kotlin/KEEP/blob/jsr-305/proposals/jsr-305-custom-nullability-qualifiers.md[Kotlin support for JSR 305 annotations]
available as of https://blog.jetbrains.com/kotlin/2017/08/kotlin-1-1-4-is-out/[1.1.4 release]
+ Reactor nullability annotations provide null-safety for the whole Reactor API to Kotlin developers,
with the advantage of dealing with `null` related issues at compile time.

For now, one needs to use a `-Xjsr305-annotations=enable` flag (specified via the
`freeCompilerArgs` property with Maven or Gradle Kotlin plugins), but that should become
the default behavior in an upcoming release of Kotlin.

[NOTE]
====
Make sure to http://search.maven.org/#artifactdetails%7Ccom.google.code.findbugs%7Cjsr305%7C3.0.2%7Cjar[include JSR-305 JAR]
until Kotlin 1.1.5 is released (it will fix https://youtrack.jetbrains.com/issue/KT-19419[KT-19419]).


Support for generic type arguments, varargs and array elements is still work in progress,
see https://youtrack.jetbrains.com/issue/KT-19592[KT-19592] and
https://youtrack.jetbrains.com/issue/IDEA-153093[IDEA-153093] for up-to-date
informations.
====

