=== `subscribe` Method Examples

This section contains minimal examples of each of the five signatures for the
`subscribe` method. Here is an example of the basic method with no arguments:

[source,java]
----
Flux<Integer> ints = Flux.range(1, 3); <1>
ints.subscribe(); <2>
----

<1> Set up a `Flux` that produces three values when a subscriber attaches.
<2> Subscribe in the simplest way.

The preceding code produces no visible output, but it does work. The `Flux`
produces three values. If we provide a lambda, we can make
the values visible. The next example for the `subscribe` method shows how:

[source,java]
----
Flux<Integer> ints = Flux.range(1, 3); <1>
ints.subscribe(i -> System.out.println(i)); <2>
----

<1> Set up a `Flux` that produces three values when a subscriber attaches.
<2> Subscribe with a subscriber that will print the values.

The preceding code produces the following output:

----
1
2
3
----

To demonstrate the next signature, we intentionally introduce an error, as
shown here:

[source, java]
----
Flux<Integer> ints = Flux.range(1, 4) <1>
      .map(i -> { <2>
        if (i <= 3) return i; <3>
        throw new RuntimeException("Got to 4"); <4>
      });
ints.subscribe(i -> System.out.println(i), <5>
      error -> System.err.println("Error: " + error));
----

<1> Set up a Flux that produces four values when a subscriber attaches.
<2> We need a map so that we can handle some values differently.
<3> For most values, return the value.
<4> For one value, force an error.
<5> Subscribe with a subscriber that includes an error handler.

We now have two lambda expressions: one for the content we expect and one for
errors. The preceding code produces the following output:

----
1
2
3
Error: java.lang.RuntimeException: Got to 4
----

The next signature of the `subscribe` method includes both an error handler and
a handler for completion events, as shown here:

[source,java]
----
Flux<Integer> ints = Flux.range(1, 4); <1>
ints.subscribe(i -> System.out.println(i),
    error -> System.err.println("Error " + error),
    () -> {System.out.println("Done");}); <2>
----

<1> Set up a Flux that produces four values when a subscriber attaches.
<2> Subscribe with a Subscriber that includes a handler for completion events.

Error signals and completion signals are both terminal events, one excluding
the other. To make the completion consumer work, we had to take care not to
trigger and error.

The completion matcher is a pair of empty parentheses because it matches the `run`
method in the `Runnable` interface, which has no parameters. The preceding code
produces the following output:

----
1
2
3
4
Done
----

The last signature of the `subscribe` method includes a custom `Subscriber`,
which we describe right after this bit of code, which shows how to attach a
custom `Subscriber`:

[source,java]
----
SampleSubscriber<Integer> ss = new SampleSubscriber<Integer>();
Flux<Integer> ints = Flux.range(1, 4);
ints.subscribe(i -> System.out.println(i),
    error -> System.err.println("Error " + error),
    () -> {System.out.println("Done");},
    s -> ss.request(10));
ints.subscribe(ss);
----

As you can see, we provide a custom `Subscriber` as the last argument to the
`subscribe` method. Here is that custom `Subscriber` object, which is the
simplest possible implementation of a `Subscriber`:

[source,java]
----
package io.projectreactor.samples;

import org.reactivestreams.Subscription;

import reactor.core.publisher.BaseSubscriber;

public class SampleSubscriber<T> extends BaseSubscriber<T> {

	public void hookOnSubscribe(Subscription subscription) {
		System.out.println("Subscribed");
		request(1);
	}

	public void hookOnNext(T value) {
		System.out.println(value);
		request(1);
	}
}
----

The SampleSubscriber class extends `BaseSubscriber`, which is the recommended
abstract class for user-defined `Subscribers` in Reactor. The class offers
hooks that can be overridden to tune the subscriber's behavior. By default,
it will trigger an unbounded request and behave exactly like `subscribe()`.

It is much more useful however when you want a custom request amount. To that
effect, the bare minimum implementation is to implement both `hookOnSubscribe(Subscription subscription)`
and `hookOnNext(T value)`. In this case, the `hookOnSubscribe` method prints a
statement to standard out and makes the first request. Then the `hookOnNext`
method prints a statement and processes each of the remaining requests, one
request at a time.

The `SampleSubscriber` class produces the following output:

----
Subscribed
1
2
3
4
----

NOTE: You almost certainly want to implement the `hookOnError`, `hookOnCancel`,
and `hookOnComplete` methods. You may also want to implement the `hookFinally`
method. `SampleSubscribe` is the absolute minimum implementation of a
`Subscriber` that performs bounded requests.

We'll see `BaseSubscriber` again soon.
