name: "Gradle Wrapper"
on: [push, pull_request]
permissions: read-all
jobs:
  validation:
    name: "validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # tag=v4
      - uses: gradle/actions/wrapper-validation@31ae3562f68c96d481c31bc1a8a55cc1be162f83 # tag=v3
