name: "Gradle Wrapper"
on: [push, pull_request]
permissions: {}
jobs:
  validation:
    name: "validation"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # tag=v5
      - uses: gradle/actions/wrapper-validation@0723195856401067f7a2779048b490ace7a47d7c
