name: "Gradle Wrapper"
on: [push, pull_request]
permissions: {}
jobs:
  validation:
    name: "validation"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # tag=v5
      - uses: gradle/actions/wrapper-validation@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e
        with:
          cache-provider: basic
